### ISSUE TITLE
Any video under gamato (cartoonsgr) fails to start

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#104]
As mentioned in the title, no video start under any subcategory of gamato. This is what the log says on kodi 18 (libreelec 9)
```
2022-06-01 20:27:25.303 T:139767570667264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1084, in <module>
                                                get_links(name, url, iconimage, description)
                                              File "/storage/.kodi/addons/plugin.video.cartoonsgr/default.py", line 755, in get_links
                                                flink = json.loads(ylink)['embed_url']
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
```
and this is from kodi 19 (libreelec 10)
```
2022-06-01 20:30:16.491 T:716     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: the JSON object must be str, bytes or bytearray, not NoneType
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1084, in <module>
                                                       get_links(name, url, iconimage, description)
                                                     File "/storage/.kodi/addons/plugin.video.cartoonsgr/default.py", line 755, in get_links
                                                       flink = json.loads(ylink)['embed_url']
                                                     File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
                                                   TypeError: the JSON object must be str, bytes or bytearray, not NoneType
                                                   -->End of Python script error report<--
```
Switching the domain back to http from https, because that was one of the addon's main changes for 1.0.30, has no effect on the above.

**Comment by pitsi** [comment]
As I said, ANY video. I just checked the first 10 under dubbed movies and none of them plays. Extra output from the log when selecting chip n dale.
```
2022-06-01 21:28:32.660 T:139773367133952   ERROR: GetDirectory - Error getting plugin://plugin.video.cartoonsgr/?description=%c2%ab%ce%a3%cf%84%ce%b7%ce%bd%20%cf%84%ce%b1%ce%b9%ce%bd%ce%af%ce%b1%2c%20%ce%bf%20Chip%20%ce%ba%ce%b1%ce%b9%20%ce%bf%20Dale%20%ce%b6%ce%bf%cf%85%ce%bd%20%ce%b1%ce%bd%ce%ac%ce%bc%ce%b5%cf%83%ce%b1%20%cf%83%ce%b5%20%ce%ba%ce%b9%ce%bd%ce%bf%cf%8d%ce%bc%ce%b5%ce%bd%ce%b1%20%cf%83%cf%87%ce%ad%ce%b4%ce%b9%ce%b1%20%ce%ba%ce%b1%ce%b9%20%ce%b1%ce%bd%ce%b8%cf%81%cf%8e%cf%80%ce%bf%cf%85%cf%82%20%cf%83%cf%84%ce%bf%20%cf%83%cf%8d%ce%b3%cf%87%cf%81%ce%bf%ce%bd%ce%bf%20%ce%9b%ce%bf%cf%82%20%ce%86%ce%bd%cf%84%ce%b6%ce%b5%ce%bb%ce%b5%cf%82%2c%20%ce%b1%ce%bb%ce%bb%ce%ac%20%ce%bf%ce%b9%20%ce%b6%cf%89%ce%ad%cf%82%20%cf%84%ce%bf%cf%85%cf%82%20%ce%b5%ce%af%ce%bd%ce%b1%ce%b9%20%cf%80%ce%bf%ce%bb%cf%8d%20...&iconimage=https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw185%2f7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg&mode=12&name=%5bB%5d%5bCOLOR%20white%5dChip%20%22n%20Dale%3a%20Rescue%20Rangers%20%5b%5bCOLORlime%5d2022%5b%2fCOLOR%5d%5d%5b%2fCOLOR%5d%5b%2fB%5d&url=http%3a%2f%2fgamatomovies.org%2fmovies%2fchip-n-dale-rescue-rangers%2f
2022-06-01 21:28:32.665 T:139773528946816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cartoonsgr/?description=%c2%ab%ce%a3%cf%84%ce%b7%ce%bd%20%cf%84%ce%b1%ce%b9%ce%bd%ce%af%ce%b1%2c%20%ce%bf%20Chip%20%ce%ba%ce%b1%ce%b9%20%ce%bf%20Dale%20%ce%b6%ce%bf%cf%85%ce%bd%20%ce%b1%ce%bd%ce%ac%ce%bc%ce%b5%cf%83%ce%b1%20%cf%83%ce%b5%20%ce%ba%ce%b9%ce%bd%ce%bf%cf%8d%ce%bc%ce%b5%ce%bd%ce%b1%20%cf%83%cf%87%ce%ad%ce%b4%ce%b9%ce%b1%20%ce%ba%ce%b1%ce%b9%20%ce%b1%ce%bd%ce%b8%cf%81%cf%8e%cf%80%ce%bf%cf%85%cf%82%20%cf%83%cf%84%ce%bf%20%cf%83%cf%8d%ce%b3%cf%87%cf%81%ce%bf%ce%bd%ce%bf%20%ce%9b%ce%bf%cf%82%20%ce%86%ce%bd%cf%84%ce%b6%ce%b5%ce%bb%ce%b5%cf%82%2c%20%ce%b1%ce%bb%ce%bb%ce%ac%20%ce%bf%ce%b9%20%ce%b6%cf%89%ce%ad%cf%82%20%cf%84%ce%bf%cf%85%cf%82%20%ce%b5%ce%af%ce%bd%ce%b1%ce%b9%20%cf%80%ce%bf%ce%bb%cf%8d%20...&iconimage=https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw185%2f7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg&mode=12&name=%5bB%5d%5bCOLOR%20white%5dChip%20%22n%20Dale%3a%20Rescue%20Rangers%20%5b%5bCOLORlime%5d2022%5b%2fCOLOR%5d%5d%5b%2fCOLOR%5d%5b%2fB%5d&url=http%3a%2f%2fgamatomovies.org%2fmovies%2fchip-n-dale-rescue-rangers%2f) failed
```
I also changed kodi's locale to english, but nothing changed.

**Comment by bugatsinho** [comment]
try the new update. Sorry for the late reply, i was working.

**Comment by pitsi** [comment]
No worries for the late reply. I was sleeping when you posted :P
I confirm that it works on both 18 and 19, so I am closing this issue. Thank you for the quick fix :)
