### ISSUE TITLE
[SportHD] The "Live Events" entry fails on kodi 18

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#110]
As mentioned in the title, the "live events" entry fails to start on kodi 18 and brings this error in the log
```
2022-09-04 08:45:24.770 T:140088537245440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u0142' in position 45120: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 677, in <module>
                                                get_events(url)
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 169, in get_events
                                                events = list(zip(client.parseDOM(str(data), 'li', attrs={'class': "item itemhov"}),
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 45120: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-09-04 08:45:24.892 T:140089317373696   ERROR: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=5&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2f1.livesoccer.sx%2f
2022-09-04 08:45:24.894 T:140089954474112   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=5&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2f1.livesoccer.sx%2f) failed
```
It works with no issue on kodi 19 and the url at the end of the log file does open on a web browser on the same network. Thus, I think it is something related to scrapping that fails on python2 but works on python3.
I do not use the addon frequently, so the above may have been an issue on previous versions too and I noticed it just now.

p.s. Can you also make the entries under "alternative live events" show up in chronological order?

**Comment by bugatsinho** [comment]
thanks mate i will check it now

**Comment by bugatsinho** [comment]
it works ok in my end though!
What version of addon do you have and  which device?

**Comment by bugatsinho** [comment]
New version 0.1.29 will shows events in chronological order! 
![image](https://user-images.githubusercontent.com/18536253/188318632-7377e703-633c-4f00-9715-c75273fb92eb.png)

**Comment by pitsi** [comment]
Sporthd on v0.1.28b and the log is from kodi 18.9, on libreelec 9.2.6, on an old laptop. My other device that runs kodi 18 is a tvbox running coreelec 9.2.8, but I have not tested it yet. I tested it on kodi 19.4 (pc running debian testing/unstable) and libreelec 10.0.2. 
No android devices here as you see :P 

And yes, I haven't booted anything yet so as to get the upgrade to 0.1.29

**Comment by bugatsinho** [comment]
Yes i can understand, cause i tested in Mac, Win and android TV also.

**Comment by bugatsinho** [comment]
[plugin.video.sporthdme-0.1.29a.zip](https://github.com/bugatsinho/bugatsinho.github.io/files/9485064/plugin.video.sporthdme-0.1.29a.zip)
if you can install this version and tell me if you get any errors.
PS: you can find it also in https://bugatsinho.github.io/test (use it as source to your kodi)

**Comment by pitsi** [comment]
Although v0.1.29 gave the same error, version 0.1.29a works just like before.
Thank you for the quick reply and the quick fix :)

**Comment by bugatsinho** [comment]
so v0.1.29a works for you mate ? I will push it ASAP.
thanks for the feedback

**Comment by pitsi** [comment]
Yea, v0.1.29a worked for me. If I got this right, the script was failing because of utf character "u0142", which is actually a small "L" with a diagonal line on it*? And it was failing only on linux systems? Amazing :D

*https://unicodeplus.com/U+0142

**Comment by pitsi** [comment]
Python2 did not like yesterday's upgrade to 0.1.61
```
2024-07-31 11:04:59.468 T:140133869266688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u0142' in position 15: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 852, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 836, in router
                                                get_events(params['url'])
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 101, in get_events
                                                event = "{} vs {}".format(team1, team2) if team1 and team2 else team1
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 15: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by kolekan** [comment]
char \u0142 is
![image](https://github.com/user-attachments/assets/430367e7-d772-4024-8139-db9bbfb23fb6)
but this is from my kodi 18.9 in windows 11 and there is no error for me getting the Live Events list.

**Comment by kolekan** [comment]
edit default.py in addon folder and change line 101
from
`event = "{} vs {}".format(team1, team2) if team1 and team2 else team1`
to
`event = u"{} vs {}".format(team1, team2) if team1 and team2 else team1`

**Comment by pitsi** [comment]
It worked. Thanks :)

**Comment by bugatsinho** [comment]
Because Its really hard for me to investigate this error please replace at your default.py the lines 882-885
with the above code 
`if isinstance(name, str):
        name = six.ensure_text(name)
    if isinstance(url, str):
        url = six.ensure_text(url)
    if isinstance(description, str):
        description = six.ensure_text(description)
    if isinstance(iconimage, str):
        iconimage = six.ensure_text(iconimage)
        
    url_encoded = quote_plus(url.encode('utf-8') if isinstance(url, six.text_type) else url)
    name_encoded = quote_plus(name.encode('utf-8') if isinstance(name, six.text_type) else name) 
    iconimage_encoded = quote_plus(iconimage.encode('utf-8') if isinstance(iconimage, six.text_type) else iconimage)
    description_encoded = quote_plus(description.encode('utf-8') if isinstance(description, six.text_type) else description)`

**Comment by pitsi** [comment]
Do I just add the 4 "if" conditions from the fist 8 lines and then the "if" conditions at the other 4 variables, and all of them **inside** the addDir function? Ok, no big deal. 
I just have to find matches that fail to start with the same error. For today, I see 2 matches this afternoon where the teams have non-utf8 characters in their names, so I will check it then.

**Comment by pitsi** [comment]
Well done, it works as it should! Feel free to add it on the addon when you can.
But before you do, evfancy is broken again, so have a look at that first. Info on the relevant issue report.

**Comment by pitsi** [comment]
If I make a commit for it (and one for the resolver's referer that needs to be changed), will you accept them?

**Comment by pitsi** [comment]
I am reopening this because it fails again with an "index out of range" error.
```
2025-07-10 06:52:37.249 T:140227335608064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 1187, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 1169, in router
                                                get_events(params['url'])
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 78, in get_events
                                                matches = re.findall(pattern, events.replace(',false', ''), re.DOTALL)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```
This time it happens on both python2 and python3, but the error is the same.
