### ISSUE TITLE
[SportHD] Live events list is completely empty

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#120]
As mentioned in the title, the live events list returns an empty output inside kodi. This is what the log says
```
2023-05-29 14:23:08.171 T:731      INFO <general>: initializing python engine.
2023-05-29 14:23:08.418 T:731      INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.sporthdme/default.py): script successfully run
2023-05-29 14:23:08.731 T:731   WARNING <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.sporthdme/default.py): the python script "/storage/.kodi/addons/plugin.video.sporthdme/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2023-05-29 14:23:08.731 T:731      INFO <general>: Python interpreter stopped
2023-05-29 14:23:11.002 T:735      INFO <general>: initializing python engine.
2023-05-29 14:23:11.933 T:735      INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.sporthdme/default.py): script successfully run
2023-05-29 14:23:12.249 T:735   WARNING <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.sporthdme/default.py): the python script "/storage/.kodi/addons/plugin.video.sporthdme/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2023-05-29 14:23:12.249 T:735      INFO <general>: Python interpreter stopped
```
Sporthd 0.1.32 on kodi 19.5 and 18.9 (libreelec x64 10.0.4 and 9.2.6 respectively).

**Comment by bugatsinho** [comment]
Check Twitter or telegram for updates about the addon. Use alternative

**Comment by pitsi** [comment]
Well, I am not on telegram and, no offence, I had to search a lot on your twitter profile to find any info about the addon.
It's ok though, I can wait :)

**Comment by bugatsinho** [comment]
all my tweets about my addons have #hashtags like #SPORTHD #CARTOONSGR to make your search easier.
also about SPORTHD 
![image](https://github.com/bugatsinho/bugatsinho.github.io/assets/18536253/9141002a-dc59-46f1-b895-3303aa1e153f)
meaning the website have the view that can be scraped using the alternative view(2nd choice in the addon menu)

**Comment by pitsi** [comment]
The live events list is full again. I don't know what changed on the site's side or when, but it now works as it should.
However, trying to play a stream results in this error on kodi 18 (my le 9.2.6 x64 installation this time). I don't know if it is related to some pesky character in the name of the game, but it surely is related to python2 because it does not happen on kodi 19 (le 10.0.4 on the same system).
```
2023-08-02 19:05:29.968 T:140232161371904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2630' in position 15604: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 722, in <module>
                                                get_stream(url)
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in get_stream
                                                return resolve(host, name)
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 349, in resolve
                                                xbmc.log('HTMLLLLL: {}'.format(html))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2630' in position 15604: ordinal not in range(128)
                                            -->End of Python script error report<--

```

**Comment by bugatsinho** [comment]
Which link? Cause only 1l1l and l1l1 streams work. Need to create resolvers for the new ones

**Comment by pitsi** [comment]
I did not notice that, sorry. All I remember it was a football game at 8pm local time and that I tried 5 or so random links from it.

**Comment by pitsi** [comment]
Closing because what I mentioned at the start now works as it should. I will open a new one once I get the encoding issue again. However, since I watch sports very rarely, this may never happen :P

**Comment by pitsi** [comment]
Goodmorning and merry xmas to everyone :)

I am reopeniong this because the the upgrade to 0.1.37 broke the "alternative live sports" list. Up until 0.1.36, the menu entry would work, although it would be completely blank. But after the upgrade it pops this error, on kodi 18, 19 and 20.
```
2023-12-25 12:12:01.840 T:140711139682048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: not expecting type '<type 'NoneType'>'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 806, in <module>
                                                get_new_events(url)
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 237, in get_new_events
                                                data = six.ensure_text(client.request(url, headers=headers))
                                              File "/storage/.kodi/addons/script.module.six/lib/six.py", line 939, in ensure_text
                                                raise TypeError("not expecting type '%s'" % type(s))
                                            TypeError: not expecting type '<type 'NoneType'>'
                                            -->End of Python script error report<--
2023-12-25 12:12:01.949 T:140712355682048   ERROR: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=15&name=%5bB%5d%5bCOLOR%20gold%5dAlternative%20LIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2fliveon.sx%2fprogram
2023-12-25 12:12:01.952 T:140712528230528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=15&name=%5bB%5d%5bCOLOR%20gold%5dAlternative%20LIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2fliveon.sx%2fprogram) failed
```
The domain mentioned at the end does open in a web browser, although it is a blank html index page. Its /program subfolder leads to a 404.

**Comment by bugatsinho** [comment]
Last update was only about adding the resolver of the new streams not about the alternative view. So Something changed at the source code. Thanks

**Comment by bugatsinho** [comment]
Alternative list is gone cause website is down

**Comment by pitsi** [comment]
Lol that was unexpected :/

**Comment by pitsi** [comment]
I just checked and the domain is up again, although it goes to a completely blank page this time. As for the /program subpage, it is now online too, but it shows nothing and I don't really know what it should show. 
The addon does not pop an error when selecting alternative events, just its list is blank.

**Comment by pitsi** [comment]
> Which link? Cause only 1l1l and l1l1 streams work. Need to create resolvers for the new ones Sent from Proton Mail for iOS

May I ask if you have added any other resolvers since then? Nothing seems to be playing since yesterday and I want to open a new bug report with a log, but I don't know which ones should work so as to use only them.

**Comment by bugatsinho** [comment]
s2stream should work I think

**Comment by pitsi** [comment]
Since the alternative links list has been broken for like 6+ months now and an empty menu entry serves nothing, can you remove it from the addon? Or maybe comment it out in its code?

**Comment by bugatsinho** [comment]
Is there any way to block you?😅

**Comment by pitsi** [comment]
Yes, there is a block/report option below the info of each profile, here.

![2024-04-07-194744_1280x1024_scrot](https://github.com/bugatsinho/bugatsinho.github.io/assets/5880037/bfb8a677-0c0d-490d-806d-a5936bbe57d8)

Ontopic, thank you for removing the alternative links option.
