### ISSUE TITLE
No events working, Python 'get stream' errors in log

### ISSUE THREAD

**Issue by happeeshopper** [bugatsinho/bugatsinho.github.io#128]
As title, no events are working. Log shows:

```
2023-07-29 20:32:14.644 T:8945   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 722, in <module>
                                                get_stream(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in get_stream
                                                return resolve(host, name)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 535, in resolve
                                                stream = client.parseDOM(r, 'iframe', ret='src')[-1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2023-07-29 20:32:17.949 T:8948 WARNING: Attempt to use invalid handle -1
2023-07-29 20:32:49.333 T:8963 WARNING: Previous line repeats 54 times.
2023-07-29 20:32:49.334 T:8963   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2630' in position 14130: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 722, in <module>
                                                get_stream(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in get_stream
                                                return resolve(host, name)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 349, in resolve
                                                xbmc.log('HTMLLLLL: {}'.format(html))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2630' in position 14130: ordinal not in range(128)
                                            -->End of Python script error report<--
```

I see the same problem before [here](https://github.com/bugatsinho/bugatsinho.github.io/issues/73), is this the same issue or is this a problem my end?

**Comment by bugatsinho** [comment]
select the one says 1l1l or l1l1
