### ISSUE TITLE
sportsHD links not working

### ISSUE THREAD

**Issue by mrusli70** [bugatsinho/bugatsinho.github.io#131]
All SportsHD links are not working. Cannot view any video content. With Kodi 20.2

**Comment by bugatsinho** [comment]
Addon works ok. 
Something in your end or ISP is blocking you.
Also try to share your log file

**Comment by ActuallyLike** [comment]
Having the same issue, same error each time, reinstalled, clear cache, etc. logs below. FirestickKodi 20.2 (but had same issue on 20.1)

```EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error [Errno 7] No address associated with hostname>
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
                                                       h.request(req.get_method(), req.selector, req.data, headers,
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1282, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1328, in _send_request
                                                       self.endheaders(body, encode_chunked=encode_chunked)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1277, in endheaders
                                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1037, in _send_output
                                                       self.send(msg)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 975, in send
                                                       self.connect()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1447, in connect
                                                       super().connect()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 941, in connect
                                                       self.sock = self._create_connection(
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 827, in create_connection
                                                       for res in getaddrinfo(host, port, 0, SOCK_STREAM):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
                                                       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   socket.gaierror: [Errno 7] No address associated with hostname
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 716, in <module>
                                                       get_stream(url)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in get_stream
                                                       return resolve(host, name)
                                                              ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 512, in resolve
                                                       data = six.ensure_str(client.request(host, referer=referer))
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/resources/modules/client.py", line 128, in request
                                                       response = urllib_request.urlopen(req, timeout=int(timeout))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                       return opener.open(url, data, timeout)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 519, in open
                                                       response = self._open(req, data)
                                                                  ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 536, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                       result = func(*args)
                                                                ^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
                                                       return self.do_open(http.client.HTTPSConnection, req,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
                                                       raise URLError(err)
                                                   urllib.error.URLError: <urlopen error [Errno 7] No address associated with hostname>
                                                   -->End of Python script error report<--

**Comment by bugatsinho** [comment]
Try VPN

**Comment by ActuallyLike** [comment]
Tried with VPN on and off, will try different settings in vpn

**Comment by Copyrighter** [comment]
I can confirm, links are stopped working.
Kodi v20.2 on Nvidia Shield.
https://pastebin.com/X1Pvitq5

**Comment by mrusli70** [comment]
Try to uninstall and reinstall again. Just to get the latest version of sportshd. see if it working now.

**Comment by bugatsinho** [comment]
New links 
istorm resolver is working after last update

Coolrea links don't work

**Comment by Copyrighter** [comment]
@bugatsinho 
the same problem for https://istorm.live/flash1

https://github.com/Copyrighter/kodi/blob/main/SportHD%20istorm.live

**Comment by bugatsinho** [comment]
No mate is working

**Comment by bugatsinho** [comment]
![image](https://github.com/bugatsinho/bugatsinho.github.io/assets/18536253/6d1aa03a-67bf-45df-ae32-aecab46bc9d3)

**Comment by Copyrighter** [comment]
can You tell on what Kodi version You are running?

**Comment by bugatsinho** [comment]
20.1

**Comment by Copyrighter** [comment]
hmmm ... and SportHD version is 0.1.33? 
can You try running on Kodi 20.2 version?

**Comment by Tontol1** [comment]
Hi,
I can confirm that links are not working on Kodi **20.2** (I've tested both on Linux Ubuntu and Firestick),
In attachment full kodi log file. But the relevant part looks like as follows:

```
   debug <general>: ------ Window Deinit (DialogSelect.xml) ------
   debug <general>: RESOLVE-URL: https://istorm.live/flash1
   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                        Error Type: <class 'TypeError'>
                        Error Contents: not expecting type '<class 'NoneType'>'
                            Traceback (most recent call last):
                         File "/home/userxyz/.kodi/addons/plugin.video.sporthdme/default.py", line 769, in <module>
                             get_stream(url)
                         File "/home/userxyz/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in get_stream
                             return resolve(host, name)
                         File "/home/userxyz/.kodi/addons/plugin.video.sporthdme/default.py", line 632, in resolve
                             r = six.ensure_str(client.request(url))
                         File "/home/userxyz/.kodi/addons/script.module.six/lib/six.py", line 919, in ensure_str
                             raise TypeError("not expecting type '%s'" % type(s))
                       TypeError: not expecting type '<class 'NoneType'>'
                     -->End of Python script error report<--
                                                   
   debug <general>: onExecutionDone(3, /home/userxyz/.kodi/addons/plugin.video.sporthdme/default.py)
```

[kodi.log](https://github.com/bugatsinho/bugatsinho.github.io/files/13467962/kodi.log)

**Comment by Tontol1** [comment]
ok, solved!
Now I realize that my internet provider has activated an anti-phishing technology that blocks "suspicious" links.
This is the case for istorm ones.
Solution is to disable anti-phishing filter.
