### ISSUE TITLE
SportHD wont open when clicking on Live Events

### ISSUE THREAD

**Issue by group131** [bugatsinho/bugatsinho.github.io#159]
This is from the log (Android TV):

>  EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='one.sporthd.me', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'one.sporthd.me'. (_ssl.c:1006)")))
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 467, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1096, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 642, in connect
                                                       sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
                                                       ssl_sock = ssl_wrap_socket(
                                                                  ^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 1108, in _create
                                                       self.do_handshake()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ssl.py", line 1383, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'one.sporthd.me'. (_ssl.c:1006)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 491, in _make_request
                                                       raise new_e
                                                   urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'one.sporthd.me'. (_ssl.c:1006)
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 844, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='one.sporthd.me', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'one.sporthd.me'. (_ssl.c:1006)")))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 852, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 836, in router
                                                       get_events(params['url'])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 62, in get_events
                                                       data = requests.get(url)
                                                              ^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 73, in get
                                                       return request("get", url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 59, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='one.sporthd.me', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'one.sporthd.me'. (_ssl.c:1006)")))
                                                   -->End of Python script error report<--

**Comment by group131** [comment]
Version used is 0.1.64 (2.7 repository)

**Comment by bugatsinho** [comment]
Change DNS😎😉

**Comment by group131** [comment]
I noticed now this. Don't know if it's relevant:

> 2024-09-25 22:02:06.921 T:14357   error <general>: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.sporthdme%2ffanart.jpg&iconimage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=events&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2fone.sporthd.me%2f
2024-09-25 22:02:06.923 T:13862   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.sporthdme%2ffanart.jpg&iconimage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=events&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2fone.sporthd.me%2f) failed

**Comment by bugatsinho** [comment]
Did you change your DNS;

**Comment by group131** [comment]
Tried it but but apparently I did something wrong since I lost internet connection completely. Will have to find a better way to do it tomorrow.

**Comment by group131** [comment]
OK. Changed DNS and you were correct, events screen shows properly. Some greek links did not work, but I guess it's not an add-on issue. Thanks a lot!

**Comment by bugatsinho** [comment]
try to use coolrea links for the moment
