### ISSUE TITLE
Issue with Categories DOM.

### ISSUE THREAD

**Issue by ozooha** [bugatsinho/bugatsinho.github.io#34]
See the kodi error log specific to the plugin. Let me know if you require any further clarifications.
```
> 2019-12-02 14:25:44.568 T:140103030576896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IndexError'>
>                                             Error Contents: list index out of range
>                                             Traceback (most recent call last):
>                                               File "/home/user/.kodi/addons/plugin.video.releaseBB/default.py", line 777, in <module>
>                                                 Categories(section)
>                                               File "/home/user/.kodi/addons/plugin.video.releaseBB/default.py", line 136, in Categories
>                                                 match = client.parseDOM(html, 'li', attrs={'id': 'categories-2'})[0]
>                                             IndexError: list index out of range
>                                             -->End of Python script error report<--
> 2019-12-02 14:25:44.653 T:140102984926976   ERROR: GetDirectory - Error getting plugin://plugin.video.releaseBB/?mode=Categories&section=movies
> 2019-12-02 14:25:44.662 T:140103445633728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.releaseBB/?mode=Categories&section=movies) failed
> 2019-12-02 14:25:56.173 T:140103030576896   ERROR: Unable to find plugin
> 2019-12-02 14:25:56.174 T:140103030576896   ERROR: GetDirectory - Error getting plugin://
> 2019-12-02 14:25:56.174 T:140103445633728   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
> 2019-12-02 14:25:59.970 T:140102995736320   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Esquire Network.png
> 2019-12-02 14:25:59.971 T:140102995736320   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/DR1.png
> 2019-12-02 14:25:59.976 T:140102747731712   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Rai 1.png
```

**Comment by bugatsinho** [comment]
which add-on version do you have? also always provide the log file

**Comment by ozooha** [comment]
I have the previous 1.8.4.
I guess I should have updated.
Yes I have the latest and it works.
Thanks for the speedy response.

Also is there a way to add the "Foreign movies" section from rlsbb?
Cheers.

**Comment by bugatsinho** [comment]
I will yes!
