### ISSUE TITLE
error: Cant play item after selecting match.

### ISSUE THREAD

**Issue by Last-Dance-Official** [bugatsinho/bugatsinho.github.io#36]
After selecting the match getting follow error:

```
17:46:26.926 T:546554417376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: initialization vector must be 16 bytes
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 448, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/sport365.py", line 118, in getStreams
                                                data = aes.AESModeOfOperationCBC(key, info).decrypt(s.replace(' ', '').decode('hex'))
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/aes.py", line 334, in __init__
                                                raise ValueError('initialization vector must be 16 bytes')
                                            ValueError: initialization vector must be 16 bytes
                                            -->End of Python script error report<--
```

**Comment by Last-Dance-Official** [comment]
v2.6.8 didnt fixed this? @bugatsinho

**Comment by Devqon** [comment]
I am having the same issue, with version 2.6.7

**Comment by lechu319** [comment]
last 2.6.9 in the f4m settings it doesn't work

**Comment by sjoerdju** [comment]
I get a similar error on the latest Libreelec, after clicking on a match to see the available options:

`2019-12-15 14:47:24.282 T:2391741296  NOTICE: RET IS: {u'k7': u'6A8pm1W3K1V6578gZNdF26vSpAtPv1Dr', u'i7': u'\x00'}
2019-12-15 14:47:24.282 T:2391741296  NOTICE: KEY IS: 6A8pm1W3K1V6578gZNdF26vSpAtPv1Dr
2019-12-15 14:47:24.438 T:2391741296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid Initial Value (IV), must be a multiple of 8 bytes
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 449, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/sport365.py", line 121, in getStreams
                                                decrypter = pyDes.triple_des(str(key), pyDes.CBC, str(info))
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/pyDes.py", line 709, in __init__
                                                _baseDes.__init__(self, mode, IV, pad, padmode)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/pyDes.py", line 118, in __init__
                                                raise ValueError("Invalid Initial Value (IV), must be a multiple of " + str(self.block_size) + " bytes")
                                            ValueError: Invalid Initial Value (IV), must be a multiple of 8 bytes
                                            -->End of Python script error report<--
2019-12-15 14:47:24.525 T:2576016240   ERROR: GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5df602307b3ff104492209%2f1&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d13%3a00%3a%20%5bCOLOR%20blue%5d4%20x%207.5km%20Relay%20(Hochfilzen)%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Biathlon%20%2f%20World%20-%20IBU%20World%20Cup&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d13%3a00%3a%20%5bCOLOR%20blue%5d4%20x%207.5km%20Relay%20(Hochfilzen)%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Biathlon%20%2f%20World%20-%20IBU%20World%20Cup%27%7d
2019-12-15 14:47:24.555 T:3011207184   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5df602307b3ff104492209%2f1&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d13%3a00%3a%20%5bCOLOR%20blue%5d4%20x%207.5km%20Relay%20(Hochfilzen)%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Biathlon%20%2f%20World%20-%20IBU%20World%20Cup&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d13%3a00%3a%20%5bCOLOR%20blue%5d4%20x%207.5km%20Relay%20(Hochfilzen)%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Biathlon%20%2f%20World%20-%20IBU%20World%20Cup%27%7d) failed
`

**Comment by mbebe** [comment]
Now is "AES-ECB";

**Comment by diabl0w** [comment]
> Now is "AES-ECB";
> s = link
> 
> ```
> 
> msg = unhexlify(s)
> decrypter = pyaes.Decrypter(pyaes.AESModeOfOperationECB(key))
> plain_text = decrypter.feed(msg)
> plain_text += decrypter.feed()
> 		
> src = plain_text.decode('hex')
> ```

so that is the fix? how do we fix it?

**Comment by mbebe** [comment]
I hope Bugatsinho will fix it soon. :-)

**Comment by bugatsinho** [comment]
@mbebe the problem is with the streams that now the website is using extra obfuscation and another javascript... take a look here https://pastebin.com/YGA49HNx
it's a jscrambler product so is needed a node.js to run the javascript but I don't know any free node...as I used heroku without success!

**Comment by mbebe** [comment]
It's really similar to last version. Your key and iv are correct.
Now it's AES-ECB.
For first link You should use my example.
For second (last link) there's rot13
```
xset = ['o', 'M', 'U', 'P', 'Z', 'X', 'w', 'S', 'Y', 'H', 'q', 'V', 'I', 'u', 'h', 'N'];
hset = ['5', '2', 'e', '0', '6', 'f', 'b', '9', '8', 'a', 'c', '4', '7', 'd', '1', '3'];
o=''
u=''
il=0
for first in hset:
    u+=first
    o+=xset[il]	
    il+=1
rot13=string.maketrans(o,u)
link=string.translate(iframes, rot13)
```
xset and hset are in some js.
```
_0xb41bd2();
var xset = ['o', 'M', 'U', 'P', 'Z', 'X', 'w', 'S', 'Y', 'H', 'q', 'V', 'I', 'u', 'h', 'N'];
var hset = ['5', '2', 'e', '0', '6', 'f', 'b', '9', '8', 'a', 'c', '4', '7', 'd', '1', '3'];
var xycoo = new Map([
	[_0x2b40('0x29f', 'vv4R'), _0x2b40('0x2a0', '3aZx')],
	[_0x2b40('0x2a1', '9NWf'), _0x2b40('0x2a2', 'W*%t')],
	[_0x2b40('0x2a3', 'OyBc'), _0x2b40('0x2a4', 'rUDx')],
	[_0x2b40('0x2a5', 'rUDx'), _0x2b40('0x2a6', 'N#T7')],
	[_0x2b40('0x2a7', '$3xO'), _0x2b40('0x2a8', 'q&c$')],
	[_0x2b40('0x2a9', '8^wM'), _0x2b40('0x2aa', ')rjH')],
	[_0x2b40('0x2ab', 'YaG7'), _0x2b40('0x2ac', '^$cC')],
	[_0x2b40('0x2ad', 'TU!0'), _0x2b40('0x2ae', 'P*ok')],
```
After rot13 we should decrypt this with AES-ECB with your key and iv , and we have correct link for stream.

**Comment by devilsport** [comment]
@mbebe cool how fast you found that those 2 pages of code for str_replace is just a simple  replacement table ;)

**Comment by mbebe** [comment]
key for decrypt is changed. new key: `z3qiYZrlfZ0AweKtwmKbhdcpVrcl7bPw`

**Comment by bugatsinho** [comment]
@mbebe I tried to open your zip file and I'm getting a zip file again! weird
@devilsport that was impressive

**Comment by mbebe** [comment]
[sport365.txt](https://github.com/bugatsinho/bugatsinho.github.io/files/3974032/sport365.txt)
line 107 - added key

**Comment by devilsport** [comment]
hi @mbebe these headers work fine

`curl -v -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" -H "Referer: http://h5.adshell.net/peer5" -H "Origin: http://h5.adshell.net" http://019-163.sport365.tech:43911/ls/69eb6787be396739e83271a57af6395220b4e378b7e668eb75dad337f2cccf033bc0172bef0090f45e6ad07b82a10da5ed6516d964c216c05fd69d452e72072c/5df88dd3d3807042220101/s07ohauh8nkngvhdjnv9vvaao0/5df9067325a3a/cakT380t7ThvPixoPU9xMQRKoWyz7H4Z/i`

**Comment by Nachtfalke49** [comment]
With the new sport365.txt i get the follow error:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pyaes
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 449, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/sport365.py", line 120, in getStreams
                                                import pyaes
                                            ImportError: No module named pyaes
                                            -->End of Python script error report<--

**Comment by bugatsinho** [comment]
@Nachtfalke49 the easiest way to fix that is to 
`from resources.lib import magic_aes as pyaes`

**Comment by norix92** [comment]
Any news on this problem? I still got it.. :(

**Comment by bugatsinho** [comment]
sorry no news! just use the website direct!

**Comment by vladisa123** [comment]
CD3AcbVH56n6IwpobFvcP0krupA950T7 is right key if use it in this file:

[sport365.txt](https://github.com/bugatsinho/bugatsinho.github.io/files/3974032/sport365.txt)

**Comment by Last-Dance-Official** [comment]
Dont know if it helps but v2.6.10.1 gives this error now:

```
16:16:46.502 T:544873746656  NOTICE: RET IS: {u'k7': u'cURUPHFV3og2k0yxaJEl04k9nK2Nw7TO', u'i7': u'\x00'}
16:16:46.688 T:544873746656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid padding byte
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 448, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/sport365.py", line 119, in getStreams
                                                data = decrypter.feed()
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/pyaes_new/blockfeeder.py", line 169, in feed
                                                result = self._final(self._buffer, self._padding)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/pyaes_new/blockfeeder.py", line 77, in _block_final_decrypt
                                                return strip_PKCS7_padding(self.decrypt(data))
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/resources/lib/pyaes_new/util.py", line 58, in strip_PKCS7_padding
                                                raise ValueError("invalid padding byte")
                                            ValueError: invalid padding byte
                                            -->End of Python script error report<--
16:16:47.077 T:548170543104   ERROR: GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5e2ffb47e5693405852151%2f1&foldername=%5bCOLOR%20lightgreen%5d%3e%3e%5b%2fCOLOR%5d15%3a40%3a%20%5bCOLOR%20cyan%5dArabian%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%5b%2fCOLOR%5d%20%7c%20Al%20Ain%20Abu%20Dhabi%20-%20FC%20Bunyodkor&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%3e%3e%5b%2fCOLOR%5d15%3a40%3a%20%5bCOLOR%20cyan%5dArabian%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%5b%2fCOLOR%5d%20%7c%20Al%20Ain%20Abu%20Dhabi%20-%20FC%20Bunyodkor%27%7d
16:16:47.079 T:548170543104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.live%2fen%2flinks%2f5e2ffb47e5693405852151%2f1&foldername=%5bCOLOR%20lightgreen%5d%3e%3e%5b%2fCOLOR%5d15%3a40%3a%20%5bCOLOR%20cyan%5dArabian%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%5b%2fCOLOR%5d%20%7c%20Al%20Ain%20Abu%20Dhabi%20-%20FC%20Bunyodkor&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%3e%3e%5b%2fCOLOR%5d15%3a40%3a%20%5bCOLOR%20cyan%5dArabian%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%5b%2fCOLOR%5d%20%7c%20Al%20Ain%20Abu%20Dhabi%20-%20FC%20Bunyodkor%27%7d) failed
```

**Comment by muniv11111** [comment]
Me too related issue - PKCS7 invalid padding byte...

**Comment by bugatsinho** [comment]
@muniv11111 @Last-Dance-Official  did you ever get the time to read my last comment on this issue?  probably not!

> sorry no news! just use the website direct!

**Comment by Last-Dance-Official** [comment]
@bugatsinho Yes i read it but after that u made a update so thats why im posting it didnt know u got upset or something just trying to give info about what i get..

**Comment by bugatsinho** [comment]
your answer is in the changelog 
![image](https://user-images.githubusercontent.com/18536253/73292403-01f41d80-41d0-11ea-9b7f-623257c30c08.png)

**Comment by Last-Dance-Official** [comment]
> 
> 
> your answer is in the changelog
> ![image](https://user-images.githubusercontent.com/18536253/73292403-01f41d80-41d0-11ea-9b7f-623257c30c08.png)

ah ive seen that but i was thinking u fixed the "streams could not play" so misunderstanding then :)
