### ISSUE TITLE
Sport hd has stopped working

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#57]
As I mention in the title, sport hd has stopped working for me since today. Clicking on live events or on a subcategory under sports makes this error pop up on the log
```
2020-07-31 10:04:27.619 T:140006907303680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe2' in position 5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 379, in <module>
                                                get_events(url)
                                              File "/storage/.kodi/addons/plugin.video.sporthdme/default.py", line 167, in get_events
                                                teams = '[B]{0} vs {1}[/B]'.format(home.strip(), away.strip())
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 5: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-07-31 10:04:27.694 T:140005628602112   ERROR: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=5&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=http%3a%2f%2fwww.sporthd.me%2findex.php%3f
2020-07-31 10:04:27.698 T:140007081232512   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=5&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=http%3a%2f%2fwww.sporthd.me%2findex.php%3f) failed
```
Checked on libreelec x64 9.2.3 with kodi 18.7.

**Comment by bugatsinho** [comment]
thank you! i will check it now

**Comment by bugatsinho** [comment]
update addon to 0.0.5 with some encoding fixes hope it'll work as i couldn't generate the issue.

**Comment by pitsi** [comment]
It seems to work as it used to now. Thank you for the quick response and the fix :)
