### ISSUE TITLE
SportsHD

### ISSUE THREAD

**Issue by Sandbird** [bugatsinho/bugatsinho.github.io#64]
I am getting this error all of the sudden with 0.1.4 version, on every stream. Last week everything was fine.
Using kodi 18.9 OSMC
Side note: I also have Netflix installed and i got this message also: The dependency on xbmc.python version 3.0.0 could not be satisfied.
Could it be something related ?

```
2021-01-24 20:40:56.430 T:1194307808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.sporthdme/default.py", line 434, in <module>
                                                get_stream(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.sporthdme/default.py", line 227, in get_stream
                                                return resolve(host, name)
                                              File "/home/osmc/.kodi/addons/plugin.video.sporthdme/default.py", line 312, in resolve
                                                ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', r, re.DOTALL)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

```

**Comment by vasilismi** [comment]
I have exactly the same error.

**Comment by bugatsinho** [comment]
issue fixed
