### ISSUE TITLE
PythonToCppException when trying to open any streams

### ISSUE THREAD

**Issue by jchgc2741** [bugatsinho/bugatsinho.github.io#71]
> 2021-04-14 20:55:56.177 T:7323   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 441, in <module>
                                                get_stream(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 232, in get_stream
                                                return resolve(link, name)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sporthdme/default.py", line 285, in resolve
                                                stream = client.parseDOM(r, 'iframe', ret='src')[-1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-04-14 20:55:56.312 T:7322   ERROR: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d19%3a00%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dRayo%20Vallecano%20vs%20Mirandes%5b%2fB%5d%20-%20%5bI%5dSpanish%20Segunda%20Division%20%5b%2fI%5d&iconimage=http%3a%2f%2fsporthd.live%2fimages%2ffootball.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d19%3a00%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dRayo%20Vallecano%20vs%20Mirandes%5b%2fB%5d%20-%20%5bI%5dSpanish%20Segunda%20Division%20%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS80Njc0LXJheW8tdmFsbGVjYW5vLXZzLW1pcmFuZGVzLWYxIiBzdHlsZT0icGFkZGluZzozcHg7Zm9udC1zaXplOjEycHg7Zm9udC13ZWlnaHQ6IDQwMDtib3JkZXItcmFkaXVzOjBweDtjb2xvcjojZmZiNjAwOyI%252BIExpbmsgIzEgKEVTKSA%253D
2021-04-14 20:55:56.328 T:5149   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d19%3a00%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dRayo%20Vallecano%20vs%20Mirandes%5b%2fB%5d%20-%20%5bI%5dSpanish%20Segunda%20Division%20%5b%2fI%5d&iconimage=http%3a%2f%2fsporthd.live%2fimages%2ffootball.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d19%3a00%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dRayo%20Vallecano%20vs%20Mirandes%5b%2fB%5d%20-%20%5bI%5dSpanish%20Segunda%20Division%20%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS80Njc0LXJheW8tdmFsbGVjYW5vLXZzLW1pcmFuZGVzLWYxIiBzdHlsZT0icGFkZGluZzozcHg7Zm9udC1zaXplOjEycHg7Zm9udC13ZWlnaHQ6IDQwMDtib3JkZXItcmFkaXVzOjBweDtjb2xvcjojZmZiNjAwOyI%252BIExpbmsgIzEgKEVTKSA%253D) failed

**Comment by jimjalost** [comment]
mine too

**Comment by bugatsinho** [comment]
fixed on last update thank you!
