### ISSUE TITLE
Sporthd no longer works

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#73]
As of today (or maybe earlier, because I tested it just now), sporthd no longer works.
This is what the log says when I select either of the 2 links for an event
```
2021-05-30 12:48:30.828 T:3719    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in resolve
                                                       flink = re.findall(r'''source:\s*["'](.+?)['"]''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 443, in <module>
                                                       get_stream(url)
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 227, in get_stream
                                                       return resolve(host, name)
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 321, in resolve
                                                       ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2021-05-30 12:48:30.889 T:3719     INFO <general>: Python interpreter stopped
2021-05-30 12:48:30.905 T:3718    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&iconimage=http%3a%2f%2fwww.sporthd.live%2fimages%2fmotorsport.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMSIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMxIChFTikgPC9hPiA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMiIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMyIChGUikg
2021-05-30 12:48:30.915 T:3375    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&iconimage=http%3a%2f%2fwww.sporthd.live%2fimages%2fmotorsport.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMSIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMxIChFTikgPC9hPiA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMiIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMyIChGUikg) failed
2021-05-30 12:48:33.273 T:3727     INFO <general>: initializing python engine.
2021-05-30 12:48:38.228 T:3727    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 319, in resolve
                                                       flink = re.findall(r'''source:\s*["'](.+?)['"]''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 443, in <module>
                                                       get_stream(url)
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 227, in get_stream
                                                       return resolve(host, name)
                                                     File "/home/x/.kodi/addons/plugin.video.sporthdme/default.py", line 321, in resolve
                                                       ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2021-05-30 12:48:38.288 T:3727     INFO <general>: Python interpreter stopped
2021-05-30 12:48:38.293 T:3726    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&iconimage=http%3a%2f%2fwww.sporthd.live%2fimages%2fmotorsport.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMSIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMxIChFTikgPC9hPiA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMiIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMyIChGUikg
2021-05-30 12:48:38.296 T:3375    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sporthdme/?description=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&iconimage=http%3a%2f%2fwww.sporthd.live%2fimages%2fmotorsport.png&mode=4&name=%5bCOLORlime%5d%2a%5b%2fCOLOR%5d%5bCOLORgold%5d%5bI%5d10%3a40%20AM%5b%2fCOLOR%5d%5b%2fI%5d%20%5bB%5dItalian%20Grand%20Prix%20%20Moto%20GP%5b%2fB%5d%20-%20%5bI%5dMoto%20GP%5b%2fI%5d&url=bGluazwvaT4gPC9zcGFuPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOyA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMSIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMxIChFTikgPC9hPiA8YSBocmVmPSJodHRwOi8vbGl2ZS5jZG56Lm9uZS83Mjk4LWl0YWxpYW4tZ3JhbmQtcHJpeC1mMiIgc3R5bGU9InBhZGRpbmc6M3B4O2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OiA0MDA7Ym9yZGVyLXJhZGl1czowcHg7Y29sb3I6I2ZmYjYwMDsiPiBMaW5rICMyIChGUikg) failed
```
Happens on both my debian testing x64 with kodi 19.1 and on libreelec 9.2.6 x64 with kodi 18.9.

**Comment by bugatsinho** [comment]
I will check it ASAP. thank you

**Comment by bugatsinho** [comment]
add-on update 0.1.9 fixes the issue

**Comment by martinstz** [comment]
Hi! 
As of yesterday (or maybe earlier, because I tested yesterday and now), sporthd no longer works. Please, fix it!
Thank you in advance!

**Comment by pitsi** [comment]
I confirm that too. Here is what the log says
```
2021-07-30 12:35:52.439 T:3674     INFO <general>: initializing python engine.
2021-07-30 12:35:55.822 T:3674    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.sporthdme/default.py", line 331, in resolve
                                                       flink = re.findall(r'''source:\s*["'](.+?)['"]''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.sporthdme/default.py", line 455, in <module>
                                                       get_stream(url)
                                                     File "/home/user/.kodi/addons/plugin.video.sporthdme/default.py", line 232, in get_stream
                                                       return resolve(link, name)
                                                     File "/home/user/.kodi/addons/plugin.video.sporthdme/default.py", line 333, in resolve
                                                       ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', rr, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2021-07-30 12:35:55.888 T:3674     INFO <general>: Python interpreter stopped
```
Debian testing/unstable x64, kodi 19.1. The same happens on kodi 18.9 too (libreelec 9.2.6 x64).

**Comment by bugatsinho** [comment]
It was a broken resolver for a specific link. Now the website provides other links and add-on works. thank you!
Let me know if it is broken again

**Comment by pitsi** [comment]
I tried all 4 events (5 links) that are available right now and all of them work, in both kodi 19.1 and 18.9. Thank you!
The logs above, which were taken earlier today, were from 2-3 different events.

**Comment by OracleKonsultant** [comment]
```
Kodi 21.0 x64
Python 3.14.0
<addon id="plugin.video.sporthdme" name="SportHD" version="0.1.84" provider-name="Bugatsinho">

```

And have again same error as here :
```

2026-03-26 22:56:59.763 T:9884    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 411, in resolve2
                                                       flink = re.findall(r'(https?:\/\/[^\s]+\.m3u8)', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 414, in resolve2
                                                       flink = re.findall(r'''source:\s*["'](.+?)['"]''', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 707, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 693, in router
                                                       resolve2(params['description'], params['url'])
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 416, in resolve2
                                                       ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2026-03-26 22:57:13.363 T:11720    info <general>: Skipped 1 duplicate messages..
2026-03-26 22:57:13.363 T:11720 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2026-03-26 22:57:15.887 T:21040    info <general>: Skipped 5 duplicate messages..
2026-03-26 22:57:15.887 T:21040   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 411, in resolve2
                                                       flink = re.findall(r'(https?:\/\/[^\s]+\.m3u8)', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 414, in resolve2
                                                       flink = re.findall(r'''source:\s*["'](.+?)['"]''', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 707, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 693, in router
                                                       resolve2(params['description'], params['url'])
                                                     File "C:\Users\DamirV\AppData\Roaming\Kodi\addons\plugin.video.sporthdme\default.py", line 416, in resolve2
                                                       ea = re.findall(r'''ajax\(\{url:\s*['"](.+?)['"],''', data, re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--


```

**Comment by bugatsinho** [comment]
Hi guys!!

As I told you in my last communication
My crypto wallets got hacked and I lost a big amount of my savings.
This cause i used a fake extension that "reads" the network and It would help me resolve and fix the resolvers of the streams for SportHD addon.

SO my decision after that was to stop any development for my addons. 
For everyone here who is coming to ask about issues. Sorry but it will be like that until someone else fork the addons and publish them. 

I'm really sorry for that but I dont want to know anything about Kodi. 

It was a nice journey of 10 years coding and developing. 

Stay Safe 🫶👊💪

**Comment by OracleKonsultant** [comment]
Hi,
Thx for your post.
Now I remember that while running Kodi wit your add on have reported from ESET some ssl connection to my PC which were refused automatically. So i assume this was the same issue that you have suffered but no ESET in your env...
very upset now and uninstalled Kodi from all of my computers.
This is rally weird....keep on and stay safe as well
Brg
Oracle

**Comment by bugatsinho** [comment]
You misunderstood my friend! The hack was by installing a fake extension in my browser. Kodi has nothing to do with that.
Neither my add-on.

**Comment by OracleKonsultant** [comment]
Ok. Sorry. So why did you change code that it doesn't work today. I will
restore files from 2 moths ago.... App, profile abd python.. .and see if it
works
Beg
Damir

**Comment by bugatsinho** [comment]
What are you talking about? no more updates for the addon. If it is dead its DEAD lol
