### ISSUE TITLE
SportsHD Kodi addon on OSMC fails

### ISSUE THREAD

**Issue by ca53** [bugatsinho/bugatsinho.github.io#92]
2021-12-19 19:34:06.291 T:1053    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (default.py, line 365)
                                                     File "/home/osmc/.kodi/addons/plugin.video.sporthdme/default.py", line 365
                                                       print str(ADDON_PATH) + ': ' + str(VERSION)
                                                               ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--

I changed 
print str(ADDON_PATH) + ': ' + str(VERSION) to 
print (str(ADDON_PATH) + ': ' + str(VERSION))

Also changed lines 366, 367, 368 and 369 accordingly
print ("Mode: " + str(mode))
print ("URL: " + str(url))
print ("Name: " + str(name))
print ("IconImage: " + str(iconimage))

Running SportsHD produces now the following error:
2021-12-28 18:03:27.114 T:601     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'urlparse'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.sporthdme/default.py", line 6, in <module>
                                                       import urlparse
                                                   ModuleNotFoundError: No module named 'urlparse'
                                                   -->End of Python script error report<--

I cant find´a module with this name. There is a /usr/lib/python2.7/urlparse.py but no dcript module in the addon directory.

Can you help?
Thanks

**Comment by ca53** [comment]
Update complete from repo
